# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1047569dd31415531d314d47b4129788f7302ba8f66585cf970d43f4dd56fd0f39b9e9712105fa245604b350d8eed4af20deb2480ca00cfc28b5f29c25b3bad

test:
  secret_key_base: 1b74f465cdc14efae23f9201870003a71d5ea319e3842e146df052dbc632d2767a6a266e477919b10af4ddf1e3ef0c112024f6c5deea234b8e3361d2b57525fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
